### PR TITLE
Fix AMCL url since original is no longer active

### PR DESCRIPTION
**Pull request by kathrynfejer**
Change the home-brew url to match what is currently up to date since the open source AMCL is not being supported

### CODE REVIEW

**Review by drbild — APPROVED** [review]
LGTM.

**Comment by zanebeckwith** [comment]
@drbild Would it be wise to keep the version at `4.7.0` rather than bump to `4.7.3`? (I'm asking in the context of the other PR making basically the same change for the XTT travis builds)

**Comment by drbild** [comment]
I think homebrew should be on the most recent release.  Unless you foresee a specific problem, I think we should bump to 4.7.3 and then deal with any resulting fall-out.

**Comment by drbild** [comment]
I see, our deb is still on 4.7.0.  I'm ok either way.  Eventually they all need to get to 4.7.3, right?

**Comment by zanebeckwith** [comment]
"(make the change) then deal with any resulting fall-out": you mean, my usual way of operating?

Cool, it's a patch-number difference, so we *should* be OK.

**Review by zanebeckwith — APPROVED** [review]
Thanks for finding this and fixing it!

**Pull request merged**
